#post setting
server:
  port: 9000
  
#jsp setting
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
# 포워드를 jsp 에서 tiles로 변경했으므로 주석처리

#mysql setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bit701?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    
#mybatis setting
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
  - /mapper/**/*.xml
  
   